{
  inputs,
  den,
  caden,
  ...
}:
{
  imports = [
    (inputs.den.namespace "caden" false)
  ];

  den = {
    default = {
      includes = [
        den.batteries.define-user
        den.batteries.hostname

        caden.core.reinstall
      ];

      os = _: {
        nixpkgs = {
          config.allowUnfree = true;

          overlays = [
            # A (probably very shitty) fix for `config.system.build.vmWithDisko`,
            # generated by Gemini Pro 3.1.
            (final: prev: {
              aggregateModules =
                paths:
                let
                  drv = prev.aggregateModules paths;
                  kernel = if builtins.isList paths then builtins.head paths else null;
                in
                drv.overrideAttrs (old: {
                  passthru = (old.passthru or { }) // {
                    target = if kernel != null && kernel ? target then kernel.target else "bzImage";
                  };
                });
            })
          ];
        };
      };

      nixos =
        {
          pkgs,
          ...
        }:
        {
          home-manager = {
            useGlobalPkgs = true;
            useUserPackages = true;
          };

          nix = {
            package = pkgs.lixPackageSets.latest.lix;

            settings = {
              auto-allocate-uids = true;
              auto-optimise-store = true;

              extra-substituters = [
                "https://nix-community.cachix.org"
              ];

              extra-trusted-public-keys = [
                "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
              ];

              keep-going = true;

              trusted-users = [ "@wheel" ];

              use-cgroups = true;
              use-xdg-base-directories = true;

              experimental-features = [
                "nix-command"
                "flakes"
                "cgroups"
                "auto-allocate-uids"
              ];
            };
          };
        };
    };

    schema = {
      user =
        { lib, ... }:
        {
          config = {
            classes = lib.mkDefault [ "homeManager" ];
          };
        };
    };
  };
}
